# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' lse
#' The function returns the lease square estimate of model Y = X*beta + epsilon. 
#'
#' @author Jingyi Lin
#' @param X is the design matrix including the intercept
#' @param Y is the response variable
#' @return \code{lse}
#' @export
lse <- function(X, Y) {
    .Call('_rbootstrap_lse', PACKAGE = 'rbootstrap', X, Y)
}

model_predict <- function(Y, X, x_new) {
    .Call('_rbootstrap_model_predict', PACKAGE = 'rbootstrap', Y, X, x_new)
}

rcppeigen_hello_world <- function() {
    .Call('_rbootstrap_rcppeigen_hello_world', PACKAGE = 'rbootstrap')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_rbootstrap_rcppeigen_outerproduct', PACKAGE = 'rbootstrap', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_rbootstrap_rcppeigen_innerproduct', PACKAGE = 'rbootstrap', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_rbootstrap_rcppeigen_bothproducts', PACKAGE = 'rbootstrap', x)
}

#' VecInnerProd
#' The function returns the inner product of two vector z = x.T*y. 
#'
#' @author Jingyi Lin
#' @param X is a vector
#' @param Y is a vector
#' @return \code{z}
#' @export
VecInnerProd <- function(x, y) {
    .Call('_rbootstrap_VecInnerProd', PACKAGE = 'rbootstrap', x, y)
}

#' VecSum
#' The function returns the sum of two vector z = x+y. 
#'
#' @author Jingyi Lin
#' @param X is a vector
#' @param Y is a vector
#' @return \code{z}
#' @export
VecSum <- function(x, y) {
    .Call('_rbootstrap_VecSum', PACKAGE = 'rbootstrap', x, y)
}

